### ISSUE TITLE
RunQueryFilter uses incorrect operand

### ISSUE THREAD

**Issue by KoenVerbeeck** [fulldata-git/ADFMonitoring#4]
The runqueryfilter for the runfilterparamaters in the request body uses an incorrect operand.

`RunQueryFilter queryFilter = new RunQueryFilter()
            {
                Operand = "RunStart",
                OperatorProperty = "Equals",
                Values = new List<string> { "InProgress" }
            };`

This means you're filtering on RunStart (a date) with the string "InProgress". This will always return no results.

**Comment by HenkvdValk-FullData** [comment]
Reviewed code fixed in #7,  
Thanks Koen! Do lets us know if anything else pops up.
