### ISSUE TITLE
SQL Database Objects missing

### ISSUE THREAD

**Issue by KoenVerbeeck** [fulldata-git/ADFMonitoring#5]
At one point a database call is made to a stored proc. This code is not provided, along with any other database objects.

` using (System.Data.SqlClient.SqlConnection connectionAzureDB = new SqlConnection("conn str"))
            {
                var serilaizedModel = JsonConvert.SerializeObject(modelList);
                var values = new { AdfPipeLineMonitoringData = "data model to be inserted" };
                var sqlResults = await connectionAzureDB.QueryAsync("[Internal].[usp_AzureADFPipeLinesExecutionData]", values, commandTimeout: 0, commandType: CommandType.StoredProcedure);
                connectionAzureDB.Close();
            }`

**Comment by fulldatagit** [comment]
Hi Koen,

Thanks a lot for helping us out of testing the repo from your end and identifying this miss from our side. The pull request has now been raised to add the missing SQL SP. https://github.com/fulldata-git/ADFMonitoring/pull/6

Thanks,
Team FullData
